### ISSUE TITLE
Ignore node_modules

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#110]
Not sure what exactly this error means, maybe it's a symlink or something? But in any case, we should probably ignore `node_modules` for now.

```
> 19vitehmrtest@0.0.0 edit
> vzcode

node:fs:1437
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, scandir '/home/curran/repos/stealth-prototypes/23BookScatterPlots/node_modules/is-wsl/node_modules/.bin/is-docker'
    at Object.readdirSync (node:fs:1437:3)
    at computeInitialDocument (file:///home/curran/repos/stealth-prototypes/23BookScatterPlots/node_modules/vzcode/src/server/computeInitialDocument.js:31:8)
    at file:///home/curran/repos/stealth-prototypes/23BookScatterPlots/node_modules/vzcode/src/server/index.js:24:25
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/home/curran/repos/stealth-prototypes/23BookScatterPlots/node_modules/is-wsl/node_modules/.bin/is-docker'
}

Node.js v19.4.0
```

**Comment by natpbs** [comment]
I'd like to give this a try, @DomaDude123 are you already working on this or is it okay if I start creating a pull request? 

I think a versatile approach would be to allow the user to specify a list of paths to be ignored, and have node_modules be included by default. It would be nice to leverage the .gitignore or another similarly formatted file for that but I would consider it a separate improvement.

**Comment by DomaDude123** [comment]
I am not working on this issue. It's all yours!

**Comment by curran** [comment]
>leverage the .gitignore

Great idea! I love that approach.

PRs warmly welcome! Happy to help wherever I can.
