### ISSUE TITLE
Incremental Expansion of Folders

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#115]
There is currently a performance problem with large directories. This is because the current code recursively lists out all files and folders from the working directory.

To fix the issue, we can consider only listing out files and directories within a given folder _only after the user expands it_. That way, only the first level of the recursion would run on page load, then more would be read in as the user expands folders in the sidebar.

A great example of this is `node_modules`, which takes some time to traverse.

**Comment by curran** [comment]
This is pretty critical as it breaks when you try VZCode in any directory that has `node_modules`.

We might just need to handle or ignore symlinks. This is the error I get:

```
$ vzcode .
node:fs:1444
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, scandir '/home/curran/repos/vizhub3/migration2/node_modules/.bin/why-is-node-running'
    at Object.readdirSync (node:fs:1444:3)
    at computeInitialDocument (file:///home/curran/.nvm/versions/node/v19.1.0/lib/node_modules/vzcode/src/server/computeInitialDocument.js:47:8)
    at file:///home/curran/.nvm/versions/node/v19.1.0/lib/node_modules/vzcode/src/server/index.js:28:25
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/home/curran/repos/vizhub3/migration2/node_modules/.bin/why-is-node-running'
}

Node.js v19.1.0

```
