### ISSUE TITLE
Fix WebSocket disconnection crash

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#138]
```
Editor is live at http://localhost:3030
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [ERR_CLOSED]: WebSocket CLOSING or CLOSED.
    at WebSocketJSONStream._send (/home/curran/repos/vzcode/node_modules/@teamwork/websocket-json-stream/index.js:76:27)
    at WebSocketJSONStream._write (/home/curran/repos/vzcode/node_modules/@teamwork/websocket-json-stream/index.js:60:14)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Agent.send (/home/curran/repos/vzcode/node_modules/sharedb/lib/agent.js:254:15)
    at /home/curran/repos/vzcode/node_modules/sharedb/lib/agent.js:860:11
    at Backend.trigger (/home/curran/repos/vzcode/node_modules/sharedb/lib/backend.js:210:20)
    at Agent._handlePresenceData (/home/curran/repos/vzcode/node_modules/sharedb/lib/agent.js:854:11)
    at OpStream.<anonymous> (/home/curran/repos/vzcode/node_modules/sharedb/lib/agent.js:156:11)
Emitted 'error' event on WebSocketJSONStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v19.1.0

```

**Comment by curran** [comment]
Closed in https://github.com/vizhub-core/vzcode/pull/140
