### ISSUE TITLE
Possible EventEmitter Memory Leak

### ISSUE THREAD

**Issue by DomaDude123** [vizhub-core/vzcode#218]
Getting the following error when opening multiple tabs:

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 receive listeners added. Use emitter.setMaxListeners() to increase limit
    at p (http://localhost:3030/assets/index-e6aae4fe.js:43:19143)
    at c.addListener (http://localhost:3030/assets/index-e6aae4fe.js:43:19426)
    at new en.fromClass.decorations (http://localhost:3030/assets/index-e6aae4fe.js:98:499)
    at en.create (http://localhost:3030/assets/index-e6aae4fe.js:74:31899)
    at Pg.update (http://localhost:3030/assets/index-e6aae4fe.js:74:32287)
    at new be (http://localhost:3030/assets/index-e6aae4fe.js:76:13389)
    at QF (http://localhost:3030/assets/index-e6aae4fe.js:101:6464)
    at http://localhost:3030/assets/index-e6aae4fe.js:101:6772
    at ip (http://localhost:3030/assets/index-e6aae4fe.js:40:24283)
    at hS (http://localhost:3030/assets/index-e6aae4fe.js:40:31623)

Tried to recreate the issue but couldn't find a discernable pattern or trigger.

**Comment by curran** [comment]
Nice! Thank you for reporting.

Does it happen on page load without doing anything?

**Comment by DomaDude123** [comment]
The error only occurs when you start opening mutiple tabs.

**Comment by curran** [comment]
I'd be curious if we can reliably reproduce this.
