### ISSUE TITLE
Make AI Assisted Coding Robust to Op Errors

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#286]
From https://github.com/vizhub-core/vzcode/pull/282

It works! Amazing!

I did get a server error, though, while testing it:

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: The op is too long for this document
    at Object.skip (/home/curran/repos/vzcode/node_modules/sharedb-client-browser/dist/ot-json1-presence-umd.cjs:2807:27)
    at Object.apply (/home/curran/repos/vzcode/node_modules/sharedb-client-browser/dist/ot-json1-presence-umd.cjs:3295:33)
    at drop (/home/curran/repos/vzcode/node_modules/sharedb-client-browser/dist/ot-json1-presence-umd.cjs:2666:7722)
    at Object.apply (/home/curran/repos/vzcode/node_modules/sharedb-client-browser/dist/ot-json1-presence-umd.cjs:2666:7872)
    at Doc._otApply (/home/curran/repos/vzcode/node_modules/sharedb/lib/client/doc.js:640:29)
    at Doc._submit (/home/curran/repos/vzcode/node_modules/sharedb/lib/client/doc.js:755:10)
    at Doc.submitOp (/home/curran/repos/vzcode/node_modules/sharedb/lib/client/doc.js:861:8)
    at file:///home/curran/repos/vzcode/src/server/index.js:92:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Connection instance at:
    at /home/curran/repos/vzcode/node_modules/sharedb/lib/client/connection.js:148:20
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v19.1.0
```

This is how I produced that error:
```
//Assume relevant modules (potentially from D3) are imported

let aColor = rgb(81, 89, 194);

let b = vec2(181, 110);

let hexColor = "#ABCDE4";
/*


*/

var my_transform = d3Transform().translate([60, 60]).rotate(-28);

var group = svg.append("g").attr("transform", my_transfornm);

let a = rgb(236, 24, 24);

let c = false;

let someHTML = (
  <div id="svgcontainer">
    <svg width="300" height="300">
      <g transform="translate(60,60) rotate(-89)">
        <rect x="20" y="20" width="60" height="60" fill="green"></rect>
        <circle cx="0" cy="0" r="30" fill="red" />
      </g>
    </svg>
  </div>
);

// TODO fix the syntax
```

Hit CTRL+m

It generated this much:

```
// There are a few syntax errors in
```

It feels like it broke maybe when it hit a newline? Not sure...

Some ideas:

 * It would be great to put the op submission in a try/catch, as a first step just to make sure the server doesn't crash totally
 * Investigate the specifics around this error - I'm not sure what exactly it could be.
 * One idea is to use our `diff` utility for figuring out the ops to submit, which may (or may not) be more robust than the approach taken here
 * We may need to think about transforming the position where text is inserted based on ops submitted by users or from Prettier while the AI is generating

**Comment by curran** [comment]
Some ideas for handling simultaneous edits:

```js
shareDBDoc.on('op', (ops, source) => {
  if (source !== "AIAssist") { // Assuming this differentiates local from remote ops - this logic may not be right
    ops.forEach(op => {
      insertionCursor = type.transformPosition(insertionCursor, op);
    });
  }
});

```

See also https://github.com/ottypes/text-unicode#transforming-cursor-positions
