### ISSUE TITLE
Start vzcode failed

### ISSUE THREAD

**Issue by baurine** [vizhub-core/vzcode#368]
When starting the vzcode, it reported the following error message:

```
$ npm install -g vzcode
$ vzcode

node:fs:1452
  handleErrorFromBinding(ctx);
  ^

Error: ELOOP: too many symbolic links encountered, scandir '/Users/bao/Library/WebKit/us.zoom.xos/WebsiteData/IndexedDB/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0'
    at Object.readdirSync (node:fs:1452:3)
    at computeInitialDocument (file:///Users/bao/.nvm/versions/node/v18.16.0/lib/node_modules/vzcode/src/server/computeInitialDocument.js:47:8)
    at file:///Users/bao/.nvm/versions/node/v18.16.0/lib/node_modules/vzcode/src/server/index.js:47:25
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -62,
  syscall: 'scandir',
  code: 'ELOOP',
  path: '/Users/bao/Library/WebKit/us.zoom.xos/WebsiteData/IndexedDB/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0/v0'
}

Node.js v18.16.0
```

OS: macOS Monterey 12.5
npm version: 9.5.1

**Comment by curran** [comment]
Closing as duplicate of [#115](https://github.com/vizhub-core/vzcode/issues/115)
