### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#841]
Sometimes this error happens randomly

```
index-Cah95BwU.js:86 Uncaught RangeError: Trying to find position for a DOM position outside of the document
    at N6.posFromDOM (index-Cah95BwU.js:86:47594)
    at Ye.posAtDOM (index-Cah95BwU.js:89:13133)
    at HTMLDocument.O (index-Cah95BwU.js:91:64965)
```

![image](https://github.com/user-attachments/assets/6f39a5f1-262c-43a1-98de-06eb498ef2e5)

It might be to do with some of the hover interactions on the editor. Hopefully we could just wrap something in a try/catch and ignore the error.

**Comment by curran** [comment]
Could be the same as https://github.com/vizhub-core/vzcode/issues/793

**Comment by curran** [comment]
closing as duplicate of https://github.com/vizhub-core/vzcode/issues/793
