### ISSUE TITLE
Handle EPIPE error

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#90]
When I tried serving over NGrok, I got this error. Not sure what it means or how to reproduce, but tracking in case it comes up again.

Maybe it's a kind of non-clean closing of the WebSocket or something?

```
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writevGeneric (node:internal/stream_base_commons:143:3)
    at Socket._writeGeneric (node:net:898:11)
    at Socket._writev (node:net:907:8)
    at doWrite (node:internal/streams/writable:409:12)
    at clearBuffer (node:internal/streams/writable:564:5)
    at Writable.uncork (node:internal/streams/writable:351:7)
    at Sender.sendFrame (/home/curran/repos/vzcode/node_modules/ws/lib/sender.js:471:20)
    at Sender.send (/home/curran/repos/vzcode/node_modules/ws/lib/sender.js:359:12)
    at WebSocket.send (/home/curran/repos/vzcode/node_modules/ws/lib/websocket.js:469:18)
Emitted 'error' event on WebSocketJSONStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by curran** [comment]
Not sure how to reproduce

**Comment by curran** [comment]
Closing until we can reproduce it again
